var url = "http://localhost:8080"
window.banPhimAPI = url + "/" + "banphim";
window.loaiBanPhimAPI = url + "/" + "loaibanphim";
window.kieuKetNoiAPI = url + "/" + "kieuketnoi";
window.hangAPI = url + "/" + "hang";
window.khachHangAPI = url + "/" + "khachhang";
window.gioHangAPI = url + "/" + "giohang";
window.gioHangChiTietAPI = url + "/" + "giohangchitiet";
window.emailAPI = url + "/" + "email"
window.loginAPI = url + "/" + "authenticate"